wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.33
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 1
      - 2
      - 3
      4: 3.8.10
      5: 0.10.33
      8:
      - 1
      - 5
    visualize:
      confusion_matrix:
        panel_config:
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          panelDefId: wandb/confusion_matrix/v1
          stringSettings:
            title: ''
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: confusion_matrix_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
batch_size:
  desc: null
  value: 1024
cities:
  desc: null
  value:
  - Sydney
epochs:
  desc: null
  value: 500
features:
  desc: null
  value:
  - Rainfall
  - Pressure3pm
  - Humidity3pm
  - lon
  - WindGustSpeed
  - TempMin
lr:
  desc: null
  value: 0.01
n_days:
  desc: null
  value: 7
n_features:
  desc: null
  value: 6
oversample:
  desc: null
  value: false
r:
  desc: null
  value: 1
scheduler:
  desc: null
  value: false
